### ISSUE TITLE
update_runtime.sh cannot detect md5sum or curl on Ubuntu 14.04

### ISSUE THREAD

**Issue by corytrese** [jorgenpt/steam-runtime-helpers#2]
The has_tool() function seems to have issues on Ubuntu Linux. In spite of having both md5sum and curl available, the update_runtime.sh script failed to detect them.

I was able to get the script to work by removing the calls to has_tool().

**Comment by jorgenpt** [comment]
I haven't been updating this, and I believe the blog post as well as the repo needs to be reworked for recent versions of the steam-runtime, but I fixed the bug you describe. Not sure why this fails for Ubuntu 14.04, but I was able to reproduce.
